FROM rust:1.67.0 as builder

# Run with access to the target cache to speed up builds
WORKDIR /workspace
ADD . .

RUN rustup target add wasm32-unknown-unknown

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    cargo install wasm-pack@0.11.1 --locked

RUN --mount=type=cache,target=./target \
    --mount=type=cache,target=/usr/local/cargo/registry \
    wasm-pack build --dev --target web interop-tests

RUN --mount=type=cache,target=./target \
    --mount=type=cache,target=/usr/local/cargo/registry \
    cargo build --release --package interop-tests --bin wasm_ping

RUN --mount=type=cache,target=./target \
    mv ./target/release/wasm_ping /usr/local/bin/testplan

FROM selenium/standalone-chrome:115.0
COPY --from=builder /usr/local/bin/testplan /usr/local/bin/testplan

ENV RUST_BACKTRACE=1

ENTRYPOINT ["testplan"]
