[package]
name = "libp2p-dns"
edition.workspace = true
rust-version = { workspace = true }
description = "DNS transport implementation for libp2p"
version = "0.45.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
futures = { workspace = true }
libp2p-core = { workspace = true }
parking_lot = "0.12.5"
smallvec = "1.15.1"
tracing = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
hickory-resolver = { workspace = true, features = ["system-config"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true }
js-sys = "0.3.77"
send_wrapper = { version = "0.6.0", features = ["futures"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = { workspace = true }
url = "2.5.4"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = { workspace = true }
web-sys = { version = "0.3.77", features = ["AbortSignal", "Headers", "Request", "RequestInit", "Response", "Window", "WorkerGlobalScope"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.50"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
libp2p-identity = { workspace = true, features = ["rand"] }
tokio = { workspace = true, features = ["rt", "time"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
tokio = ["hickory-resolver/tokio"]

# Passing arguments to the docsrs builder in order to properly document cfg's.
# More information: https://docs.rs/about/builds#cross-compiling
[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[lints]
workspace = true
