use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

/// All `.proto` files to compile, relative to the workspace root.
const PROTO_FILES: &[&str] = &[
    "misc/prost-codec/src/generated/test.proto",
    "core/src/generated/envelope.proto",
    "core/src/generated/peer_record.proto",
    "identity/src/generated/keys.proto",
    "misc/webrtc-utils/src/generated/message.proto",
    "transports/noise/src/generated/payload.proto",
    "transports/plaintext/src/generated/structs.proto",
    "protocols/autonat/src/v1/generated/structs.proto",
    "protocols/autonat/src/v2/generated/structs.proto",
    "protocols/dcutr/src/generated/message.proto",
    "protocols/floodsub/src/generated/rpc.proto",
    "protocols/gossipsub/src/generated/rpc.proto",
    "protocols/gossipsub/src/generated/compat.proto",
    "protocols/identify/src/generated/structs.proto",
    "protocols/kad/src/generated/dht.proto",
    "protocols/relay/src/generated/message.proto",
    "protocols/rendezvous/src/generated/rpc.proto",
];

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("gen-proto must live two directories below the workspace root")
        .to_path_buf();

    assert!(
        root.join("Cargo.toml").exists(),
        "workspace root not found at {}",
        root.display(),
    );

    // Group proto files by parent directory (= include dir = output dir).
    let mut by_dir: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for proto in PROTO_FILES {
        let dir = proto
            .rsplit_once('/')
            .expect("proto path must contain '/'")
            .0;
        by_dir.entry(dir).or_default().push(proto);
    }

    // Compile each group with prost-build.
    for (dir, protos) in &by_dir {
        let abs_dir = root.join(dir);
        let abs_protos: Vec<PathBuf> = protos.iter().map(|p| root.join(p)).collect();

        println!("  {} file(s) in {dir}", protos.len());

        prost_build::Config::new()
            .out_dir(&abs_dir)
            .compile_protos(
                &abs_protos
                    .iter()
                    .map(|p| p.as_path())
                    .collect::<Vec<_>>(),
                &[abs_dir.as_path()],
            )
            .unwrap_or_else(|e| panic!("failed to compile protos in {dir}: {e}"));
    }

    // Generate a `mod.rs` in every output directory.
    let dirs: BTreeSet<&str> = by_dir.keys().copied().collect();
    for dir in dirs {
        write_mod_rs(&root.join(dir));
    }

    println!("Done.");
}

/// Write a `mod.rs` that re-exports every generated `.rs` file in `dir`.
///
/// Files whose stem contains dots (e.g. `gossipsub.pb.rs`) get a `#[path]`
/// attribute because dots are not valid in Rust identifiers.
fn write_mod_rs(dir: &std::path::Path) {
    let mut files: Vec<String> = std::fs::read_dir(dir)
        .unwrap()
        .filter_map(|entry| {
            let name = entry.ok()?.file_name().into_string().ok()?;
            (name.ends_with(".rs") && name != "mod.rs").then_some(name)
        })
        .collect();
    files.sort();

    let mut out =
        String::from("// Automatically generated by gen-proto. DO NOT EDIT.\n");

    for file in &files {
        let stem = file.strip_suffix(".rs").unwrap();
        if stem.contains('.') {
            let mod_name = stem.replace('.', "_");
            out.push_str(&format!("#[path = \"{file}\"]\npub mod {mod_name};\n"));
        } else {
            out.push_str(&format!("pub mod {stem};\n"));
        }
    }

    std::fs::write(dir.join("mod.rs"), &out).unwrap();
}
